### ISSUE TITLE
Automate publishing to PyPI with pbr & Travis

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#134]
We need a way to ease/automate releases management and publication to PyPI. This morning, I read [this post](http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/), and it seems to perfectly fit with our needs.

WDYT?

**Comment by jmaupetit** [comment]
As a bonus, note that this post proposes a way to solve #83.

**Comment by k4nar** [comment]
Why not. But IMO typing `python setup.py sdist bdist_wheel upload` is not that hard :) .

**Comment by jmaupetit** [comment]
The problem is PyPI credentials sharing: you or @SpotlightKid must be able to release Watson and publish this new release without sharing a single password.

**Comment by SpotlightKid** [comment]
`pbr` looks like a nice project, but I'm always a bit sceptical about technical solutions to organisational or social problems. Like @k4nar said, the actual administrative work of creating and uploading a release isn't that complicated or time consuming. The problem atm, IMHO, is that nobody seems to find the time to sit down for 2-3 hours to review the state of the project, check that the changelog is complete, build a release, install it, do some smoke tests, etc. Pushing the release after that is only a matter of minutes.

I think, instead of spending time to set up pbr, the time would be better spent writing down a checklist for preparing a release and, most of all, get the test for the CLI going, so we can have more confidence that a release doesn't break anything. Issue #5 seems to be blocked by some technicality, so let's just make it work, even if that means, adding some not-so-pretty hacks to the tests.

**Comment by SpotlightKid** [comment]
BTW, AFAIR you can add maintainers (with their own account) to a PyPI project.

**Comment by jmaupetit** [comment]
> The problem atm, IMHO, is that nobody seems to find the time to sit down for 2-3 hours to review the state of the project, check that the changelog is complete, build a release, install it, do some smoke tests, etc. Pushing the release after that is only a matter of minutes.

You are totally right, and I share the responsibility of Watson's status. I'll do my best to take needed time next week.

> BTW, AFAIR you can add maintainers (with their own account) to a PyPI project.

Sorry I missed this. You are right.

**Comment by d0ugal** [comment]
You don't need pbr to automate the releases - it just helps automate one extra bit.

The main advantage is that your releases are automated and always built in a consistent way in a clean environment.

Rolling the releases locally increases the chance of somebody running the wrong  command or accidentally including (or excluding) extra files in the release.
