### ISSUE TITLE
Add merge command

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#18]
I am using dropbox with [Mackup](https://github.com/lra/mackup) to sync watson `frames` between all my machines. In some cases, a conflict file is generated due to a missing sync when one of my machine was used off-line. Hence, it would be nice to be able to merge two conflicting watson `frames` files.

Usage may be:

```bash
$ watson merge frames frames-with-conflicts
```

By default, `merge` will output statistics about the merge operation, like:

```bash
$ watson merge frames frames-with-conflicts
120 frames will be left unchanged
12  frames will be merged
3   frame conflicts need to be resolved
```

To perform the merge operation, there is an option for that:

```bash
$ watson merge frames frames-with-conflicts --no-dry-run
120 frames unchanged
12 frames merged
Will resolve conflicts:
frame 8804872:
< {
<     "project": "tailordev",
<     "start": "2015-07-28 09:33:33",
<     "stop": "2015-07-28 10:39:36",
<     "tags": [
<         "intern",
<         "daily-meeting"
<     ]
< }
---
> {
>     "project": "tailordev",
>     "start": "2015-07-28 09:33:33",
>     "stop": "**2015-07-28 11:39:36**",
>     "tags": [
>         "intern",
>         "daily-meeting"
>     ]
> }
Select the frame you want to keep: left or right? (L/r)
...
```

I am widely open to discussion & suggestions.

**Comment by waynew** [comment]
I'm a huge fan of this idea. My first professional project actually dealt with this same pattern, and to wrap my head around the problem I came up with a drawing that provides all of the scenarios one could encounter:

<img width="395" alt="screenshot 2015-10-30 07 50 25" src="https://cloud.githubusercontent.com/assets/189750/10846109/0aeefa70-7edb-11e5-997c-8c37fd6f5581.png">

I'm not sure if, realistically, you'd see all of the same sorts of conflicts here or not.

**Comment by jmaupetit** [comment]
I don't think we will face such complexity as each frame as a uuid.

**Comment by waynew** [comment]
Aren't the conflicts based on time span, though?

**Comment by jmaupetit** [comment]
Most of the time you will have missing frames. Conflicting frames (identified by their uuid) will differ in their end date time. This will be interactively solved as illustrated before.

Given the initial scenario (cross computer sync failure with a single user), I don't think we need to check on time spans. But I might be wrong. My approach is maybe too simple and less generic than the one you proposed.

**Comment by waynew** [comment]
Ah, I see what you were talking about now.

I just bumped into maybe an edge case. I forgot to switch tasks in watson just now, so I started a new frame, and because I'm not aware of the ability to edit the current frame (other than manually, and translating time is too big of a pain) I just restarted the same project, so it looked something like this:

    1 5:30-5:55 apollo 14
    2 5:55-6:00 apollo 13
    3 6:00-now   apollo 13

but I really started at 5:45, so I edited 2 and changed the start time to `5:45`. Now I have

    1 5:30-5:55 apollo 14
    2 5:45-6:00 apollo 13
    3 6:00-now   apollo 13
 
So I've got a time overlap. Is this something that watson should care about? My thought is yes, with maybe a config setting for `allow_time_overlap` or something for those who would want to be doing two things at once :trollface:

**Comment by jmaupetit** [comment]
You are right. At this time we don't care about time overlap due to frame edition, but maybe it's something we need to check on.

**Comment by EmilMaric** [comment]
In Dropbox, does the conflicted copy of the `frames` file something like [this](https://www.dropbox.com/en/help/36)? If so, would the solution to this issue have to use some sort of glob pattern like `frames\ \(*conflicted\ copy*` in order to get the name of the conflicted frames file, since the name of conflicted frames file would be unique for each user?

Or would it be better to have the user specify the name of the conflicted frames file in the command itself? For example, we could have:
```bash
$ watson merge frames frames-with-conflicts --conflict-file frames\ \(emilmaric\'s\ conflicted\ copy\ 2015-11-26\)
```

Lastly, this also opens up the question of what to do when there is more than one conflicted frames file in the Dropbox folder. Do we merge all of them in together, or should the command only do one merge at a time?

**Comment by jmaupetit** [comment]
To clarify usage, `frames` and `frames-with-conflicts` are paths to files. I a first approach, I think only one merge at a time should be considered.
