### ISSUE TITLE
Exclude some tags or projects from a log/report

### ISSUE THREAD

**Issue by raphaelfournier** [TailorDev/Watson#232]
I like to track my whole workweek, including breaks. But, when I want a log or report, I often would like to separate personal errands and breaks from working frames. I implemented that feature this morning:

![2018-11-06-140509_1088x283_scrot](https://user-images.githubusercontent.com/986560/48066629-693e4000-e1ce-11e8-9cc9-607e78e30fdb.png)

It seems to work in combination with `-T` as expected, ie `watson log -T tag1 -S tag2` will display (only) frames containing tag1 and (among them) remove those containing tag2.

 I open the issue so that you may comment. For instance, I would like opinions on the use of `-S`. I have yet to properly format my work into a pull request, and currently I only added the `-S` option for tags with the `log` command (so the `report` is to be done).

**Comment by jmaupetit** [comment]
Hi @raphaelfournier! It looks like a great feature :clap: I wonder why did you choose the capital 'S' letter for this option? :grin: and not let's say `-e` for exclude?

**Comment by raphaelfournier** [comment]
I think `-e` is good, but if the feature is implemented for both tags and projects, one may not recall what `-e` will exclude (tags, projects, both). So my idea was to have a letter close to the existing ones, `-S` (or `-U`) paired with `-T` for tags, `-Q` (or `-O`) for projects. 
But I have to admit that `-S` feels a bit weird/not intuitive at all.

**Comment by jmaupetit** [comment]
Okay, now I see the underlying logic :+1: And what about `-e` for tags and `-E` for projects?

**Comment by raphaelfournier** [comment]
Sorry for the late reply. I will start hacking more efficiently after I have completed my setup (see #238), and will probably implement the feature with `-e`/`-E` as you suggested. 

As a side note: I'm not completly aware of the good practice for leaving issues opened, I guess I should leave it until there's a PR merged to reference and then close. Is it ok?

**Comment by jmaupetit** [comment]
> I guess I should leave it until there's a PR merged to reference and then close. Is it ok?

Yes! You can add "Fix #232" to the description of the PR that will close this issue.

**Comment by davidag** [comment]
Options for excluding tags/projects in the `report` command were added in #288, specifically:

* `--ignore-project TEXT` | Reports activity for all projects but the given ones. You can ignore several projects by using the option multiple times. Any given project will be ignored
* `--ignore-tag TEXT` | Reports activity for all tags but the given ones. You can ignore several tags by using the option multiple times. Any given tag will be ignored.

Nevertheless, there are a couple of things missing to be able to say this issue is completed:

* The feature was not implemented for `watson log` nor `watson aggregate`.
* No short-option was defined for `--ignore-project` or `--ignore-tag`.

Finally, there is also the open PR #225 which kind of does something similar, but different.

**Comment by raphaelfournier** [comment]
I think #288 and #225 and this issue address exactly the same problem. In this issue, I proposed something but did not implement it till the end, like #225. Since #288 is complete, I guess both #225 and #232 (this one) should be closed.

**Comment by jmaupetit** [comment]
#225 implements the same tag/project exclusion for both the report and log command. It is still missing for the log command, and #225 implements it...
