### ISSUE TITLE
Integration with Toggl

### ISSUE THREAD

**Issue by powellc** [TailorDev/Watson#29]
I use Toggl to track my entire day's time. It would be awesome to be able to leverage Watson to track time and have it sync with Toggl.

I'm a python developer by trade, so I'll fork this bad boy and see what I can do.

**Comment by willdurand** [comment]
Hi! We are working on an Open Source backend for synchronizing Watson data on a sort of dashboard. Basically, Watson makes API calls to a backend that is "Watson-compliant", not the other way around. Not sure on how to deal with that to be honest.

**Comment by powellc** [comment]
That would be close, but the reality I've had in using a time tracker is that it has to be available where I am. Thus, if I'm with a client, having a CLI time tracker isn't awesome. So a dashboard per-se isn't enough for me.

BUT, I was day dreaming about a sort of open-source toggl, and if it sync'd with Watson, that'd be pretty cool.

**Comment by willdurand** [comment]
At some point, this dashboard might allow "writes" too.

**Comment by willdurand** [comment]
Closing in favor of #40

**Comment by gustawdaniel** [comment]
Link to backend of Watso Backend (that now exists)

> https://crick.io/

Link to toggl API docs

> https://github.com/toggl/toggl_api_docs

Model of event in watson

```
    {
        "id": "96aee7e132de410db7faf5ab53ec78ba", 
        "project": "watson-learn", 
        "start": "2019-01-06T00:10:05+01:00", 
        "stop": "2019-01-06T01:07:07+01:00", 
        "tags": [
            "dev", 
            "learn"
        ]
    }
```

Model of event in toggle

```
    {
        "description": "New time entry",
        "start": "2013-02-12T15:35:47+02:00",
        "billable": false,
        "wid": 31366,
        "pid": 9012,
        "duration": 1200,
        "stop": "2013-02-12T15:35:57+02:00",
        "tags": [
         	"billed"
        ],
        "id": 4269795
    }
```

is described there: 

> https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md

What is the same:

+ id - should be mapped during synhronisation
+ tags 
+ project (in watson) -> pid ( id of project in toggle, you can read that pis is project id there https://github.com/toggl/toggl_api_docs/blob/master/chapters/tasks.md ) 
+ start
+ stop

These was all watson fields. Toggl has also:

+ description - I describe it later, because of it is important thing
+ billable - we no need sync this field because of Watson not implement it
+ wid - (workspace id - shortcut described there: https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md)
+ duration - this will not be synced because of it is calculated field (from stop and start)

*Description*. 

Description is basic concept in toggle, we can say that in watson it is replaced by project, but should not be. In my opinion independent field for description should be better. This feature was described there. 

> https://github.com/TailorDev/Watson/issues/93

It is probably that in watson it will be called message, because of proposition of @jmaupetit from 25 Feb 2016 typed in issue #93.

Now pull request introducing messages (toggl description) is under review:

> https://github.com/TailorDev/Watson/pull/119

When will be finished we can reopen this issue and give them `feature request` label if community want this feature.

**Comment by jmaupetit** [comment]
Thank you for this complete analysis @gustawdaniel! Indeed, we are not far from a pluggable backend compatibility...
