### ISSUE TITLE
handle pause/resume

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#3]
It would be great to have a pause/resume functionality. This would actually have the same effect than `start`, `stop` then `start` again, but without having to specify the project each time.

**Comment by k4nar** [comment]
Maybe we don't need to add a third "paused" state, but we just need a `restart` command ? Or maybe another way to say "start the same project as last time, with the same tags".

**Comment by waynew** [comment]
`restart` is the command I expected to be there... but wasn't :P

**Comment by SpotlightKid** [comment]
I was also looking for `pause` / `resume` commands but I guess just `restart` would work too (one can always define shell aliases).

**Comment by EmilMaric** [comment]
Hey, just wanted to say that I've began using this tool and I think it's great! I'm of the mindset that `pause`/`resume` would offer more control over just `restart`. I've got a bit of time now, and I've looked through the code and have an idea on how to tackle this issue. Would anyone object to assigning me to this issue?

**Comment by willdurand** [comment]
@EmilMaric Sure! Waiting for your PR :-)

**Comment by jmaupetit** [comment]
:+1:

**Comment by waynew** [comment]
@EmilMaric not sure if you have made any progress on this yet. Lack of a restart capability bothered me enough that I just went ahead and implemented it here: https://github.com/waynew/Watson/commit/bd33493067642f4d9cb345e52e703e4fa5914366

I pretty much just took the code from the `start` and `edit` commands and fixed the names. Note that this particular commit *does* depend on either #43 being merged in, or the config value being set.

**Comment by SpotlightKid** [comment]
Wouldn't it be better to call `cli.start()` from `cli.restart()` (with appropriate args), so there's no code duplication?

This would also allow to add new tags on restarting.

**Comment by waynew** [comment]
@SpotlightKid probably. I'm not familiar enough with Click (yet) to know if calling decorated code works fine... I seem to recall having some issues doing that in the past.

I definitely disliked the duplicated code and wanted to shift that out into something else, but pragmatism won out this morning. I needed to do something else and that was the quickest thing to get me the `restart` capabilities :trollface: 

Weren't you the one who suggested extracting the bulk of the CLI code into a more testable <something>, since there are currently no real tests for the cli processing? That's a sentiment that I agree with wholeheartedly.

**Comment by SpotlightKid** [comment]
@waynew I imported your `personal/restart` branch into my fork (btw, would be nice, if you don't put unrelated commits like the last one in there), and adapted the code. See [here]()

One slightly strange (or maybe unexpected) behaviour of the `start` command with `stop_on_start` option enabled is that it will stop the current project and then restart it with the same tags. I think, most user probably want something like "if there is no current frame, restart the old one, if there is one, leave it running".

I didn't bring up the issue about testing the CLI, but I agree as well :)

**Comment by waynew** [comment]
I'm not sure that I follow - are you talking about running `start` with the same project/tags twice in a row?

**Comment by SpotlightKid** [comment]
No, start then restart, with no stop in-between (maybe accidentally), but `stop_on_start` enabled.

**Comment by waynew** [comment]
*ah*

So restarting with nothing when you currently have something running?

Hm... Are you sure that starts the existing project? Unless I misunderstood it seems like it should be restarting the last frame, e.g.

    $ watson start foo +bar +baz +bang
    $ watson start knights +gallahad +robin +bedevere
    $ watson restart

I would expect that to start `foo` (with associated tags). Does it restart `knights`?

**Comment by SpotlightKid** [comment]
You're right, it restarts `foo`. That's even worse, err, "unexpected".

(Only tested with the same projects and tags before, so I didn't notice.)

**Comment by waynew** [comment]
That may be *unexpected*, but it's definitely behavior that works well for me. Frequently I'll be doing X, then I get Y in that needs to be triaged/done, then I want to go back to X. And if X is a long running task, say over the course of day, it's highly likely that I may be interrupted a few times. So it's kind of nice to be able to do something like

    $ watson start primary task +issue-42 +client
    $ watson start secondary task +issue-99 +other client

time passes.... :hourglass: 

    $ watson restart

Now I'm back working on `primary task`

    $ watson start tertiary task +issue-1337 +client

more time passes.... :hourglass: 

    $ watson restart

And now I'm back working on `primary task again`. Pretty slick. Initially surprising, yes, but I think it's surprising in a *good* way :)


If we're worried about accidentally creating a bunch of frames for the same project/tags, would #18 handle that?

**Comment by SpotlightKid** [comment]
Ok, I see your use case, but it's definitely not what I would expect from a `restart` command and not a replacement for the `pause`/ `resume` functionality this issue was originally about, I think.

The more I think about it, `restart` shouldn't do anything at all, if a frame is already started. This can be done by putting this at the start of `restart()`:

```
    if watson.current:
        raise click.ClickException("{} {} {}".format(
            style('error', "Project already started:"),
            style('project', watson.current['project']),
            style('tags', watson.current['tags'])))
```

Example:

```
$ watson restart
Error: Project already started: watson [issue3]
```

For your use case, maybe, instead of passing a frame ID, you could add support for passing a (negative) frame index to the `restart` command?

**Comment by waynew** [comment]
It already takes the frame ID - it just defaults to the *last* frame.

There are two use cases for `restart` that I can think of:

- I'm keeping track of my time for work. When I go to lunch I `stop` work on the project, and when I come back from lunch I `restart` the last thing I was doing. Like so:

    $ watson stop
    # Go to lunch...
    $ watson restart

- My typical case, where I'm working on one thing, do a context switch, and then come back. It's very similar to the previous case, but instead of `stop` I'm recording my time. For instance, I might do:

    $ watson start lunch +personal
    # Go to lunch...
    $ watson restart
    Stopping project lunch [personal], started an hour ago. (id: 32cb8a7) 
    Restarting Herring [red, work] at 16:29

This seems pretty consistent to me. Sure, at first it's a bit surprising, but I think it's more surprising in a pleasant, "Oh, yeah, that *is* what I'd like to do," kind of way, rather than a, "Wait, what in the world just happened here? Why would it let me do **that**??" Sort of way.

I'm not sure if these use cases were different than what you'd get out of `pause`/`resume`, or if they obviate their necessity. For me, I was just missing `restart` :)

**Comment by SpotlightKid** [comment]
> It already takes the frame ID - it just defaults to the last frame

I wrote frame *index*, i.e. `-1` or `-10`.

**Comment by waynew** [comment]
As it is, by default it *won't* stop anything unless you explicitly set `stop_on_start`.

If the existing behavior is that reprehensible, let's just add another config setting: `stop_on_restart`. Then you get to tell it to stop before you restart something, and I don't have to ;)

**Comment by SpotlightKid** [comment]
I've submitted an alternative PR in #49, to show my idea how `restart` should work.

BTW, @waynew, in this implementation your use case can be achieved with `watson restart --stop -- -2`.

**Comment by jmaupetit** [comment]
I am sorry @waynew but I think @SpotlightKid is right. This is what I expected when I first declared this issue. If @k4nar or @willdurand also approves PR #49 we will merge @SpotlightKid implementation.
