### ISSUE TITLE
Parsing of Times is broken and breaks `watson stop --at`

### ISSUE THREAD

**Issue by MaxG87** [TailorDev/Watson#343]
Commit 9b3b40d624db024fcdd6d385138679fcae3058fd broke the correct parsing of times, at least for

    watson stop --at HH:MM

**Comment by prat0088** [comment]
It appears that change was meant to unify all datetime parsing logic.  Previously the command took a Time object but now it takes a DateTime.  [The documentation](https://github.com/TailorDev/Watson/commit/9b3b40d624db024fcdd6d385138679fcae3058fd#diff-02eaf97f516ebdc69a92f82aba3a40faR248) is out-of-date because it describes the date as optional, but it is now required.  

Perhaps the answer is to update the command's documentation.

**Comment by davidag** [comment]
@MaxG87 I'm not able to reproduce this issue. Could you add some more information? What Python version are you using? What's the error message? Thank you!

**Comment by MaxG87** [comment]
I managed to reproduce the problem. It turns out that this is due to a problem with installation. The parsing of times is fine. Sorry for the fuzz.
