### ISSUE TITLE
suggested new features

### ISSUE THREAD

**Issue by lesar** [TailorDev/Watson#349]
I sugest features like project client name to make simple to get time to make invoice.  
Now I put client name in tag and then report filtering by tag.  

at every start I suggest to put a optionally short description of activity session. only tag is not easy  way.  

best regards,
Leonardo

**Comment by prat0088** [comment]
@lesar I think you're asking for a way to add notes to each time you start and/or stop a timing session.  Is that right?  If so I've implemented the feature in #337 and it's waiting on review.  There are instructions in the PR for how to install it locally if you want to play around with it, but please make a backup of your data first because the file format might change before it's merged, corrupting your data.

**Comment by lesar** [comment]
Yes @prat0088 is what I was like to found (like git message).  
My Idea for client name can be achieved putting it on tag, like I will do just now.  

The client name part can be add to plugin for invoice referring a tag choose by user conf.  

I will wait official dist to use feature #337.  

best regards,
Leonardo
