### ISSUE TITLE
pip not in Ubuntu 20.04 LTS anymore...

### ISSUE THREAD

**Issue by DrOteonu-Nanquanu** [TailorDev/Watson#389]
Only pip3 seems to be in the Ubuntu 20.04 repositories. An update of the installation manual would be much appreciated.

I tried

`pip3 install td-watson`

and this works on Ubuntu 20.04. May save other people quite some time figuring this out if it would be in the manual ! Thanks.

**Comment by jmaupetit** [comment]
:thinking: that's a bit too Ubuntu-specific. I think `pip` may point to installed python 2 distros for those who upgrade from old ubuntu releases.

But you are right: maybe we should mention in the documentation that `pip3` may be used instead of `pip` on some GNU/Linux distros. Do you have time to submit a PR for that? :pray:

**Comment by DrOteonu-Nanquanu** [comment]
Done..! ;-)

**Comment by jmaupetit** [comment]
FTR it has been fixed in #390
