### ISSUE TITLE
How to import entries exported with `watson log`?

### ISSUE THREAD

**Issue by lx4r** [TailorDev/Watson#460]
Hi,
I have exported entries from Watson with `watson log --month --json --current`. Now I want to add those entries to my Watson installation on another machine from the exported JSON file. Is that possible? If yes, how? I have tried to use `watson merge` without success.

Thanks in advance for the help :).

**Comment by ericguirbal** [comment]
The frames are stored in the `frames` file in your application folder. You can merge them with a simple editor. Otherwise, for something easy to script, I suggest you to use [jq](https://github.com/stedolan/jq) a command-line json processor (probably available in your repositories if you use Linux). The commands in the following procedure are for a linux box.

1. Open a terminal.
2. Go in your application folder. For example, 
`cd ~/.config/watson`.
3. Make a backup of your `frames` file: 
`mv frames frames20220203.backup`.
4. Copy the `frames` file from the other machine in your application folder. Rename it `frames-othermachine`.
5. Merge the files `frames20220203.backup` and `frames-othermachine` with output in `frames`:  
`jq -s '[.[][]]' frames20220203.backup frames-oldmachine > frames`.
6. Done.

**Comment by lx4r** [comment]
@ericguirbal Thanks for the reply, I didn't know about the `frames` file before 👍 . I ended up writing a small script to add the entries from my JSON export to the local Watson instance by executing `watson add` for each entry as I couldn't get merging my entries into the `frames` file to work.
