### ISSUE TITLE
Repository tags pattern

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#59]
At this time, release tags are not homogeneous. Two patterns have been pushed: `1.0.1` and `v1.1.0`. I would prefer a simple, non-prefixed pattern like: `1.0.1`.

Do you agree?

When we will have chosen a pattern, we will need to fix existing tags and force push them. Since some tags point to `master` and others to `develop`, this needs to be done along with #58.

**Comment by Ins1ne** [comment]
+1 for simple non-prefixed pattern

**Comment by willdurand** [comment]
It does not make any sense to force push existing tags. Also, prefixing tags is much better than you think. If you want to create a branch for a given release (say for security reasons), you will get stuck because of tag names, as both are just pointers anyway. Let's use `vX.Y.Z` for the next releases. But leave existing commits alone..

**Comment by jmaupetit** [comment]
After a brief discussion with @willdurand, we decided to use non prefixed patterns. `1.1.0` release tag has been fixed.
