### ISSUE TITLE
Add some options to the report command

### ISSUE THREAD

**Issue by themouette** [TailorDev/Watson#64]
Watson report is great, but experience can be smoother with a few more options:

Proposition 1:

* `--this-day` (alias `--today`): report for current day
* `--past-day` (alias `--yesterday`): report for day before today
* `--this-week`: report for current month (from monday)
* `--past-week`: report for last month (from monday)
* `--this-month`: report for current month (from 1st)
* `--past-month`: report for last month (from 1st)
* `--this-year`: report for current year (from January 1st)
* `--past-year`: report for last year (from January 1st)

Proposition 2:

* `--day` report for current day
* `--day -1` report for yesterday
* `--week` report for current week
* `--week -1` report for past week
* `--month` report for current month
* `--month -1` report for past month
* `--year` report for current year (starting January 1st)
* `--year -1` report for past year (starting January 1st)

**Comment by k4nar** [comment]
Yes, we had such aliases in mind when building the `report` command. We didn't do it though because we wanted to take some time to think about what was needed.
I think now it is time to consider it more deeply.

Your first proposition seems pretty good. However I'm think it will introduce a lot of noise, and there is the risk that at some point we have tons of `--past-quarter` and such.

We were considering adding some "natural language" parser for dates, cf #10. We couldn't find any satisfying solution, but maybe we could have a compromise: we could add a `--for` option, understanding a list of sentences, like `past year`, `this month`, etc…
That way we would be able to do `watson report --for past quarter`.

**Comment by jmaupetit** [comment]
@themouette: thank you for this suggestion! I think @k4nar is right here: something like `--for today` seems like a good compromise. We need to put some efforts on #10.

**Comment by k4nar** [comment]
@jmaupetit : #10 is a bit different because its about date parsing. Here we want time frame parsing, which could actually be far easier.

**Comment by SpotlightKid** [comment]
PR #130 added support for timespan selection option for the current year, month, week and day to the `report` and `log` commands. This covers most if what's requested here. Further timespan "presets" can be implemented with a bit of clever shell programming, IMHO.

So I'm closing this as fixed. If you disagree, feel free to reopen bit (preferably with a PR :) ).

**Comment by themouette** [comment]
Thank you.

Le 30 juil. 2016 17:27, "Christopher Arndt" <notifications@github.com> a
écrit :
