### ISSUE TITLE
Add an optional (relative) time to the start and stop commands

### ISSUE THREAD

**Issue by yloiseau** [TailorDev/Watson#75]
Some times, you realize you have started working on a task/project without tracking it. It would be nice to have a CLI option to indicate that you actually started earlier. For instance

```
watson start --for 10min 'World Domination Project' +'first analysis'
watson start --since 14:35 'Work on personal organisation'
```

or something similar. 

In the same way, the option can be useful for the `stop` command (e.g. back from lunch and see that your task is still started).

**Comment by willdurand** [comment]
:+1:

**Comment by jmaupetit** [comment]
Current workflow to solve this kind of issues is:

```shell
# Start your project with tags
$ watson start "World Domination Project" +"first analysis"
# Edit current (running) frame
$ watson edit

# or (for stop)
$ watson stop
$ watson edit
```

`--for` and `--since` options seems cool, but I hope this won't be too confusing.

**Comment by jmaupetit** [comment]
@yloiseau I am afraid this would add too much complexity to the `start` command.
@k4nar @SpotlightKid WDYT?

**Comment by k4nar** [comment]
I don't use watson enough to have a valid opinion on this. But FYI, for now we don't have any option for `watson start`, so there's room for some :) .

**Comment by SpotlightKid** [comment]
I'm using the workflow with `watson edit` described above fairly and I have to admit it's a bit cumbersome. I would welcome a way to at least set the absolute start time directly with `watson start`. Or maybe the `watson edit` command should take options to change a frame non-interactively?

**Comment by loonies** [comment]
:+1: 

At times it happens to me as well.

**Comment by larsborn** [comment]
+1

**Comment by sglessard** [comment]
👍

**Comment by braincow** [comment]
I hacked a quick implementation proposal for this kind of feature at https://github.com/TailorDev/Watson/pull/224

**Comment by k4nar** [comment]
Indeed, finding a good naming is essential. I do find @yloiseau's version more intuitive though :) .

What do you find confusing in the current proposal?

**Comment by tanius** [comment]
@k4nar Two things are confusing me:

* I am used to command line options being named either as "intended actions" (like "add last …" in my proposal) or to make sense in English natural language when taken together with the command ("start at" in my proposal). Trying to apply such an interpretation to "start for …" and "start since …" fails, so it's not intuitive to me.

* I am not an English native speaker, so the semantic difference between "for" and "since" is also not intuitive to me. I know it, but I always have to think for a few seconds to make sense of the difference when seeing both side-by-side such as in the proposed options.

**Comment by patcon** [comment]
As example of another tool having an interface for this, `doing` CLI has something similar and very semantic:
https://brettterpstra.com/projects/doing/#adding-entries

```
doing now --back 15m working on GH-13
```

**Comment by patcon** [comment]
Also, a `watson amend` command (inspired by `git commit --amend`) might make an intuitive way to noninteractively make edits to last entry, include `watson amend --back 15m` and similar such modifications

**Comment by jmaupetit** [comment]
I'm not sure we have to add a new command that would be an `edit` alias (even if I like the `amend` semantic). 

:+1: for the `--back 15mn` option; hence non interactively editing the current frame would look like the following:

```
$ watson edit --back 15mn
```

**Comment by davidag** [comment]
Just for the sake of inspiration and because there are more issues related to dates, I think it might be interesting to learn how other projects are dealing with dates.

For example:
- https://taskwarrior.org/docs/durations.html
- https://timewarrior.net/docs/backdated.html

In my opinion, all date issues should be tackled at once to develop a consistent solution through all Watson commands.

**Comment by prat0088** [comment]
I just ran into this problem and was going to file an issue.

`stop` already supports `--at`.  For symmetry, why not add `--at` to start?  Otherwise the routine for stopping a late task would be

`watson stop --at 14:00`

but the routine for starting a late task would be

`watson start someproj`
`watson edit --back 15m`

I like the `--at` syntax in `stop` because it is concise and doesn't make me invoke two commands.

**Comment by patcon** [comment]
> I like the --at syntax in stop because it is concise and doesn't make me invoke two commands. Why not add --at to start to make it symmetric to stop?

I would expect `--back` and `--at` would be interchangeable (though not functionally so) and so could both be implemented for `start` and `stop` -- relative vs absolute times :)

I would venture that `--back` should always work relative to current time. (e.g., rather than "pushing back" an existing state, like the start time.)

For examples:

```
# with absolute time
watson start --at 14:00

# with relative time
watson start --back 15m

# start a task, backdating start time to 15m ago
watson start --back 15m someprog

# modify start time of running task (relative to time edit command run)
watson start someprog
# < ~5 min of time passes >
watson edit --back 20m

# modify stop time of last stopped task
watson stop
# < ~5 min of time passes >
watson edit --back 20m
```

My assumption (though this should be vetted), is that `edit` modifies the start time for running tasks, and the stop time for stopped tasks.
