### ISSUE TITLE
Propose git client-side hooks

### ISSUE THREAD

**Issue by danielpetisme** [TailorDev/Watson#97]
You can easily track a feature dev if you listen to the `git checkout -b`, `git commit` & `git push` commands. Would be nice to link watson and a standard git flow.
I don't know in which order it makes the more sense
`git checkout -b my-feature` triggers `watson start my-feature` or the reverse...

git proposes [client-side hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#Client-Side-Hooks), it can be a pragmatic approach.

The aim is to have a seamless (almost transparent) time tracking for git users

**Comment by SpotlightKid** [comment]
I doubt it would be possible to find a one-size-fits-all approach for this. Does everybody start working on a feature by creating a branch? What about research or investigation that comes before it? Is work really done after the last commit? How do you know it is the last one? The merge might happen much later, because often the commiter is not the same person as the merger.

If you you want to link watson to a software development workflow, I think a ticket tracker would be a much better candidate for integration than a VCS.

**Comment by k4nar** [comment]
It's not the first time this features comes up, and my point of view so far has always been pretty close to what @SpotlightKid said. It really depends on your workflow, so we will probably never ship a feature like that with Watson.

However, if you make git hooks which work for you, don't hesitate to share them with the community, we'll link them in the doc :) .

**Comment by jmaupetit** [comment]
@danielpetisme: as @k4nar said, feel free to submit your project's repository in this thread! We will add it to the documentation. In the meantime, I'll close this issue.
