### ISSUE TITLE
Edit command fails if frame id is numerical

### ISSUE THREAD

**Issue by bryanjswift** [TailorDev/Watson#98]
I currently have a frame `1612702` that I'd like to edit but `watson edit 1612702` treats it as a relative frame number and I get "Error: Frame index 1612702 not in range."

**Comment by SpotlightKid** [comment]
I can see [where](https://github.com/TailorDev/Watson/blob/master/watson/cli.py#L641) in the code that happens, it first tries to interpret the frame ID as an integer and assumes, if that succeeds, that it is a frame index.

We could probably fix this by using different heuristics, but actually this bug highlights issues with the way access to the internal frame database is modelled. IMO `watson.frames.Frames` tries to cram too much into the dictionary-style interface: get frame by frame ID, get frame by index and get frame data by "column" name. Since they are all handled by the method that implements the index operator (`[]`), there is currently no interface to specify whether you want to look up a frame by ID or by index.

This also makes access by frame ID rather inefficient and it gets slower as the frame database grows.

My first instinct would be to try to change the internal datatype of `Frames` into an ordered dict and provide explicit methods for access by index etc. But I'll have to take a closer look.

**Comment by k4nar** [comment]
Yeah, I might have tried to be too clever here. However, if we stick with the current design, the error actually lies in the edit command: https://github.com/TailorDev/Watson/blob/master/watson/cli.py#L640-L651 . I have an idea how to fix that, I'll make a PR later today.

FIY @SpotlightKid I did a first implementation using [tablib](https://github.com/kennethreitz/tablib), but it wasn't working as I wished so I tried to do something similar but simpler. I don't have strong feelings about it, and I agree that the current design might be confusing and not very efficient in certain cases.
I guess your right, an OrderedDict might be a far better option. I'll try to give it a shot.
